In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
X,y = load_diabetes(return_X_y=True)

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 2 ,test_size=0.2)

In [5]:
reg = LinearRegression()

In [6]:
reg.fit(X_train,y_train)

LinearRegression()

In [7]:
print(reg.intercept_)
print(reg.coef_)

151.88334520854633
[  -9.16088483 -205.46225988  516.68462383  340.62734108 -895.54360867
  561.21453306  153.88478595  126.73431596  861.12139955   52.41982836]


In [8]:
y_pred = reg.predict(X_test)

In [9]:
r2_score(y_test ,y_pred)

0.4399387660024645

In [60]:
import random
class MBGDRegressor:
    
    def __init__(self,batch_size ,learning_rate= 0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # initialize the coefficients and intercepts
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            for j in range(int(X_train.shape[0] / self.batch_size)):
                
                # Generating random numbers for the given batch size
                idx = random.sample(range(X_train.shape[0]), self.batch_size)
                
                y_hat = np.dot(X_train[idx] , self.coef_) + self.intercept_
                intercept_der = (-2) * np.mean(y_train[idx]-y_hat) 
                self.intercept_ = self.intercept_ - (self.lr*intercept_der)

                coef_der = (-2/self.batch_size) * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_ , self.coef_)
         
    def predict(self,X_test):
        return np.dot(X_test,self.coef_ ) + self.intercept_

In [61]:
int(X_train.shape[0]/10)

35

In [89]:
mgdr = MBGDRegressor(batch_size=int(X_train.shape[0]/20) , epochs = 100 ,learning_rate =0.1)

In [90]:
mgdr.fit(X_train,y_train)

150.3986215652853 [  47.83899069  -81.15889935  365.57909714  262.07264467   11.22235725
  -35.06345113 -180.08233187  130.3698812   328.84340221  125.85341084]


In [91]:
y_pred = mgdr.predict(X_test)

In [92]:
r2_score(y_test,y_pred)

0.43891644531894947

17

In [17]:
import random 
random.sample(range(100),10)

[61, 96, 70, 98, 9, 91, 48, 31, 56, 66]

In [18]:
random.sample(range(X_train.shape[0]), 10)

[154, 123, 164, 153, 52, 198, 204, 287, 131, 3]

In [19]:
X_train[[154, 123, 164, 153, 52, 198, 204, 287, 131, 3]]

array([[-0.00188202, -0.04464164,  0.03367309,  0.12515848,  0.02457414,
         0.02624319, -0.01026611, -0.00259226,  0.02671426,  0.06105391],
       [-0.00188202,  0.05068012,  0.01427248, -0.07452802,  0.0025589 ,
         0.00620169, -0.01394774, -0.00259226,  0.01919903,  0.00306441],
       [-0.00914709, -0.04464164, -0.05686312, -0.05042793,  0.02182224,
         0.04534524, -0.02867429,  0.03430886, -0.00991896, -0.01764613],
       [ 0.01628068,  0.05068012,  0.00241654, -0.00567061, -0.00569682,
         0.01089891, -0.05076412,  0.03430886,  0.02269202, -0.03835666],
       [-0.02367725, -0.04464164,  0.03043966, -0.00567061,  0.08236416,
         0.09200436, -0.01762938,  0.07120998,  0.03304707,  0.00306441],
       [ 0.04897352,  0.05068012,  0.08109682,  0.02187235,  0.04383748,
         0.06413415, -0.05444576,  0.07120998,  0.03243323,  0.04862759],
       [ 0.02354575, -0.04464164,  0.06169621,  0.05285819, -0.03459183,
        -0.04891244, -0.02867429, -0.00259226

# ***How to use Mini Batch Gradient descent from Scikit learn***

In [93]:
from sklearn.linear_model import SGDRegressor

In [94]:
sgd = SGDRegressor(learning_rate='constant' , eta0=0.2)

In [96]:
batch_size = 35
for i in range(100):
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx] , y_train[idx])

In [97]:
sgd.coef_

array([   3.04210185, -131.84737515,  479.15966354,  271.10347392,
        -28.7788636 ,  -88.62197125, -191.22841743,  110.04684546,
        382.86703047,  125.99680835])

In [98]:
sgd.intercept_

array([148.69750243])

In [99]:
y2_pred = sgd.predict(X_test)

In [100]:
r2_score(y_test,y2_pred)

0.4571808431197223